// Comprehensive 100+ Sample Dataset for Faculty of Technology, University of Ruhuna
// 10 Categories x 10 High Quality Sample Items Each = 100 Opportunities total

const categories = [
  "Scholarships",
  "Internships",
  "Jobs",
  "Training",
  "Financial Support",
  "Mental Health",
  "Accommodation",
  "Transport",
  "Events",
  "Volunteering",
];

const departments = [
  "Department of Information & Communication Technology",
  "Department of Engineering Technology",
  "Department of Biosystems Technology",
  "General",
];

const generateCategoryData = () => {
  const dataset = [];
  let idCounter = 1;

  // 1. SCHOLARSHIPS (10 Items)
  const scholarships = [
    {
      title: "Faculty Dean's Academic Merit Scholarship 2026",
      description: "Annual merit stipend awarded to top 5% undergraduates across ICT, ET, and BST departments based on 1st & 2nd semester GPA.",
      category: "Scholarships",
      department: "General",
      location: "Dean's Office, FoT Campus",
      deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["GPA >= 3.70", "Full-time FoT undergraduate", "No disciplinary record"],
      contactEmail: "deansoffice@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/scholarships/merit",
      tags: ["Merit", "Stipend", "GPA", "Dean's List"],
    },
    {
      title: "Ceylon Chamber of Commerce STEM Undergraduate Grant",
      description: "Financial grant of LKR 180,000 to assist low-income undergraduates in Engineering Technology with equipment and tuition.",
      category: "Scholarships",
      department: "Department of Engineering Technology",
      location: "Colombo / Matara",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Family annual income < LKR 600,000", "ET Undergraduate"],
      contactEmail: "grants@chamber.lk",
      applicationUrl: "https://fot.ruh.ac.lk/grants/chamber",
      tags: ["Financial Aid", "Engineering", "Grant"],
    },
    {
      title: "Women in ICT Technology Leadership Fellowship",
      description: "Special grant for female undergraduates pursuing Information & Communication Technology degrees, including 1-on-1 industry mentorship.",
      category: "Scholarships",
      department: "Department of Information & Communication Technology",
      location: "ICT Dept Labs & Remote",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Female ICT Undergraduate 2nd/3rd Year", "Motivation letter"],
      contactEmail: "womenintech@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/grants/women-ict",
      tags: ["Women in Tech", "ICT", "Mentorship"],
    },
    {
      title: "Mahapola Higher Education Merit Bursary Supplement",
      description: "Additional monthly allowance for Mahapola recipient students facing economic hardships due to travel costs.",
      category: "Scholarships",
      department: "General",
      location: "Student Affairs Branch",
      deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Mahapola Bursary Card", "Student ID"],
      contactEmail: "studentaffairs@ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/bursary",
      tags: ["Mahapola", "Bursary", "Financial Aid"],
    },
    {
      title: "Biosystems Research Innovation Grant 2026",
      description: "Research funding grant up to LKR 250,000 for innovative undergraduate projects in smart agriculture and post-harvest technology.",
      category: "Scholarships",
      department: "Department of Biosystems Technology",
      location: "BST Research Center",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["BST 3rd or 4th Year Student", "Project proposal abstract"],
      contactEmail: "bst.research@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/bst/grant",
      tags: ["Biosystems", "Research", "Agriculture"],
    },
    {
      title: "Dialog Axiata Digital Technology Scholarship",
      description: "Full laptop funding and LKR 15,000 monthly allowance for high-achieving ICT students with an interest in mobile and cloud systems.",
      category: "Scholarships",
      department: "Department of Information & Communication Technology",
      location: "Colombo / Remote",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["ICT 2nd Year Student", "GPA >= 3.50"],
      contactEmail: "dialog.scholarships@dialog.lk",
      applicationUrl: "https://fot.ruh.ac.lk/dialog-grant",
      tags: ["Dialog", "Laptop", "Cloud"],
    },
    {
      title: "Alumni Association Hardship Support Grant",
      description: "One-time financial assistance of LKR 50,000 funded by FoT Alumni for students in urgent need of accommodation or medical fees.",
      category: "Scholarships",
      department: "General",
      location: "Kamburupitiya Campus",
      deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Application form", "Recommendation from Head of Dept"],
      contactEmail: "alumni@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/alumni/grant",
      tags: ["Alumni", "Emergency", "Grant"],
    },
    {
      title: "Sri Lanka Telecom Cloud Engineering Bursary",
      description: "Monetary support and free fiber broadband connections for undergraduates doing remote final-year projects.",
      category: "Scholarships",
      department: "Department of Information & Communication Technology",
      location: "Matara / Remote",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Final year ICT or ET student", "Internet access need"],
      contactEmail: "slt.campus@slt.lk",
      applicationUrl: "https://fot.ruh.ac.lk/slt-bursary",
      tags: ["SLT", "Broadband", "Cloud"],
    },
    {
      title: "Green Technology Sustainable Energy Scholarship",
      description: "Sponsorship for Engineering Technology students working on solar PV optimization and hydro power micro-turbines.",
      category: "Scholarships",
      department: "Department of Engineering Technology",
      location: "ET Labs",
      deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["ET 3rd/4th Year Student", "Solar / Energy project focus"],
      contactEmail: "et.green@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/et/green-grant",
      tags: ["Renewable Energy", "Solar", "ET"],
    },
    {
      title: "International Japanese Language & Tech Exchange Grant",
      description: "Travel stipend and course fees covered for FoT undergraduates participating in 3-week virtual software engineering exchange with Japan.",
      category: "Scholarships",
      department: "General",
      location: "Virtual / Tokyo",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Basic Japanese N5/N4 preferred", "FoT Undergrad"],
      contactEmail: "japan.exchange@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/japan-exchange",
      tags: ["Japan", "Exchange", "Global"],
    },
  ];
  scholarships.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 2. INTERNSHIPS (10 Items)
  const internships = [
    {
      title: "Full-Stack Software Engineering Internship - Virtusa",
      description: "6-month paid internship working on Java Spring Boot and React enterprise web applications.",
      category: "Internships",
      department: "Department of Information & Communication Technology",
      location: "Colombo / Hybrid",
      deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Java / React knowledge", "3rd Year ICT Undergrad"],
      contactEmail: "careers@virtusa.com",
      applicationUrl: "https://fot.ruh.ac.lk/careers/virtusa",
      tags: ["Virtusa", "React", "Java", "Paid"],
    },
    {
      title: "Embedded IoT & Smart Sensors Internship - Dialog Axiata",
      description: "Practical industrial placement developing ESP32 hardware nodes for telemetry and environmental sensing.",
      category: "Internships",
      department: "Department of Engineering Technology",
      location: "Dialog Tech Lab / Matara",
      deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["C/C++ Arduino & Microcontrollers", "Circuit design"],
      contactEmail: "internships@dialog.lk",
      applicationUrl: "https://fot.ruh.ac.lk/careers/dialog-iot",
      tags: ["IoT", "ESP32", "Hardware"],
    },
    {
      title: "Data Science & Python Machine Learning Intern - WSO2",
      description: "Join WSO2 analytics team building predictive models for API gateway traffic and log analysis.",
      category: "Internships",
      department: "Department of Information & Communication Technology",
      location: "Colombo / Remote",
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Python, Pandas, Scikit-learn", "Good SQL skills"],
      contactEmail: "jobs@wso2.com",
      applicationUrl: "https://fot.ruh.ac.lk/careers/wso2",
      tags: ["WSO2", "Python", "Data Science"],
    },
    {
      title: "Post-Harvest Quality Control Trainee - FoodTech Lanka",
      description: "Hands-on industrial training in sensory analysis, packaging QA, and moisture control for agricultural produce.",
      category: "Internships",
      department: "Department of Biosystems Technology",
      location: "Galle Industrial Zone",
      deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["BST Undergrad 3rd Year", "Lab safety certified"],
      contactEmail: "qa@foodtech.lk",
      applicationUrl: "https://fot.ruh.ac.lk/careers/foodtech",
      tags: ["Biosystems", "QA", "Food Science"],
    },
    {
      title: "QA Automation Engineering Intern - Sysco LABS",
      description: "Learn Cypress and Selenium web test automation frameworks working alongside senior QA leads.",
      category: "Internships",
      department: "Department of Information & Communication Technology",
      location: "Colombo / Remote",
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["JavaScript fundamentals", "Attention to detail"],
      contactEmail: "careers@syscolabs.com",
      applicationUrl: "https://fot.ruh.ac.lk/careers/sysco",
      tags: ["QA", "Automation", "Cypress"],
    },
    {
      title: "CAD Modeling & Mechanical Draftsperson Trainee - DSI Samson",
      description: "Design 3D molds and mechanical components using SolidWorks for industrial manufacturing.",
      category: "Internships",
      department: "Department of Engineering Technology",
      location: "Galle / Matara",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["SolidWorks or AutoCAD proficiency"],
      contactEmail: "engineering@dsi.lk",
      applicationUrl: "https://fot.ruh.ac.lk/careers/dsi",
      tags: ["CAD", "SolidWorks", "Manufacturing"],
    },
    {
      title: "Cyber Security & Network Defense Intern - SLT-MOBITEL",
      description: "Monitor SOC network traffic logs, assist with firewall policy audits, and vulnerability assessments.",
      category: "Internships",
      department: "Department of Information & Communication Technology",
      location: "Colombo / Matara SOC",
      deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["CCNA or Linux networking basics"],
      contactEmail: "secops@slt.lk",
      applicationUrl: "https://fot.ruh.ac.lk/careers/slt-sec",
      tags: ["Cyber Security", "Networking", "SOC"],
    },
    {
      title: "Tissue Culture & Biotechnology Trainee - Department of Agriculture",
      description: "6-month practical training in micropropagation and plant tissue culture at regional lab.",
      category: "Internships",
      department: "Department of Biosystems Technology",
      location: "Labuduwa Agriculture Research Station",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["BST Biotechnology specialization"],
      contactEmail: "labuduwa@agridept.gov.lk",
      applicationUrl: "https://fot.ruh.ac.lk/careers/agri-lab",
      tags: ["Biotech", "Tissue Culture", "Agriculture"],
    },
    {
      title: "UI/UX & Mobile App Design Intern - Zone24x7",
      description: "Design interactive wireframes and modern mobile UI components using Figma for retail solutions.",
      category: "Internships",
      department: "Department of Information & Communication Technology",
      location: "Colombo / Hybrid",
      deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Figma portfolio", "User empathy"],
      contactEmail: "design@zone24x7.com",
      applicationUrl: "https://fot.ruh.ac.lk/careers/zone24x7",
      tags: ["UI/UX", "Figma", "Design"],
    },
    {
      title: "Robotics & Automation Trainee - Lalan Rubbers Tech",
      description: "Maintenance and PLC programming for automated conveyor belts and robotic arms.",
      category: "Internships",
      department: "Department of Engineering Technology",
      location: "Biyagama Export Processing Zone",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["PLC programming", "ET Mechatronics focus"],
      contactEmail: "automation@lalanrubbers.com",
      applicationUrl: "https://fot.ruh.ac.lk/careers/lalan",
      tags: ["Robotics", "PLC", "Mechatronics"],
    },
  ];
  internships.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 3. JOBS (10 Items)
  const jobs = [
    {
      title: "Part-Time IT Lab Technical Assistant - FoT Campus",
      description: "Assist lab instructors during student practical sessions, software installation, and PC troubleshooting.",
      category: "Jobs",
      department: "Department of Information & Communication Technology",
      location: "ICT Lab 1 & 2, FoT Campus",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT 2nd/3rd year student", "Good OS & hardware skills"],
      contactEmail: "ict.head@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/lab-assistant",
      tags: ["Part-Time", "Campus Job", "IT Support"],
    },
    {
      title: "Freelance React & Node.js Developer (Part-Time)",
      description: "Remote weekend part-time work for a Matara software agency developing e-commerce web portals.",
      category: "Jobs",
      department: "Department of Information & Communication Technology",
      location: "Matara / Remote",
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["React.js", "Node.js", "MongoDB"],
      contactEmail: "hr@mataratech.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/freelance-react",
      tags: ["Freelance", "React", "Node.js", "Weekend"],
    },
    {
      title: "Equipment Maintenance Assistant - ET Department",
      description: "Hourly paid job servicing hydraulic test benches and CNC machines under lab technician guidance.",
      category: "Jobs",
      department: "Department of Engineering Technology",
      location: "Heavy Machinery Workshop, FoT",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["ET student", "Safety gear required"],
      contactEmail: "et.lab@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/et-tech",
      tags: ["ET", "CNC", "Machinery"],
    },
    {
      title: "Junior WordPress Developer & Site Maintainer",
      description: "Manage and update news posts for local Southern Province business websites. Flexible 10 hrs/week.",
      category: "Jobs",
      department: "Department of Information & Communication Technology",
      location: "Remote",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["WordPress CMS experience", "HTML/CSS basics"],
      contactEmail: "info@southernweb.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/wordpress",
      tags: ["WordPress", "Remote", "Part-Time"],
    },
    {
      title: "Soil Testing & Agricultural Sample Collector",
      description: "Weekend field job gathering soil samples across Southern Province farms for biosystems research.",
      category: "Jobs",
      department: "Department of Biosystems Technology",
      location: "Matara / Kamburupitiya",
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["BST student", "Valid motor vehicle license"],
      contactEmail: "bst.soil@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/soil-test",
      tags: ["Biosystems", "Fieldwork", "Weekend"],
    },
    {
      title: "Campus Library Digital Cataloguer",
      description: "Digitize and index academic journals and research theses into DSpace library repository.",
      category: "Jobs",
      department: "General",
      location: "FoT Library",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Undergrad", "Accurate typing skills"],
      contactEmail: "library@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/library",
      tags: ["Library", "Part-Time", "Data Entry"],
    },
    {
      title: "Graphic Designer & Social Media Content Creator",
      description: "Create banners and promotional flyers for faculty symposiums and student club events.",
      category: "Jobs",
      department: "General",
      location: "Remote / Campus",
      deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Photoshop / Illustrator or Canva proficiency"],
      contactEmail: "media@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/graphic-designer",
      tags: ["Design", "Canva", "Media"],
    },
    {
      title: "3D Printing & Laser Cutter Operator",
      description: "Operate the FoT Innovation Cell 3D printers and assist students with model slicing.",
      category: "Jobs",
      department: "Department of Engineering Technology",
      location: "Innovation Cell, Building B",
      deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Cura / 3D printing experience"],
      contactEmail: "innovation@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/3d-printer",
      tags: ["3D Printing", "Maker", "ET"],
    },
    {
      title: "Weekend Computer Hardware Repair Technician",
      description: "Diagnose and fix laptop motherboard faults and screen replacements at Matara Tech Arcade.",
      category: "Jobs",
      department: "Department of Information & Communication Technology",
      location: "Matara Town",
      deadline: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Hardware troubleshooting skills"],
      contactEmail: "techarcade@matara.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/hardware-tech",
      tags: ["Hardware", "Repair", "Matara"],
    },
    {
      title: "Smart Greenhouse Operations Assistant",
      description: "Monitor hydroponics nutrient levels and automated drip irrigation valves on weekends.",
      category: "Jobs",
      department: "Department of Biosystems Technology",
      location: "FoT Agri Park",
      deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["BST student", "Punctual weekend availability"],
      contactEmail: "greenhouse@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/jobs/greenhouse",
      tags: ["Hydroponics", "Greenhouse", "BST"],
    },
  ];
  jobs.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 4. TRAINING (10 Items)
  const training = [
    {
      title: "Kubernetes & Cloud DevOps Intensive Bootcamp",
      description: "Hands-on weekend bootcamp covering Docker containerization, Helm charts, and AWS EKS cluster deployment.",
      category: "Training",
      department: "Department of Information & Communication Technology",
      location: "Virtual Lab & Auditorium",
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Basic Linux command line knowledge"],
      contactEmail: "devops.training@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/devops",
      tags: ["Docker", "Kubernetes", "AWS", "DevOps"],
    },
    {
      title: "Ethical Hacking & Web Penetration Testing Masterclass",
      description: "Learn OWASP Top 10 vulnerabilities, SQL injection, and Burp Suite tools in a controlled sandbox environment.",
      category: "Training",
      department: "Department of Information & Communication Technology",
      location: "Advanced Cyber Security Lab",
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Student ID"],
      contactEmail: "cyber.workshop@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/security",
      tags: ["Cyber Security", "Ethical Hacking", "OWASP"],
    },
    {
      title: "Microcontroller Board Soldering & PCB Design Training",
      description: "Design custom 2-layer PCBs using EasyEDA and master surface-mount component soldering.",
      category: "Training",
      department: "Department of Engineering Technology",
      location: "Electronics Lab, Building B",
      deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Bring personal laptop"],
      contactEmail: "pcb.training@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/pcb",
      tags: ["PCB", "Electronics", "Soldering"],
    },
    {
      title: "Deep Learning with PyTorch & Computer Vision",
      description: "Build convolutional neural networks for object detection and image classification.",
      category: "Training",
      department: "Department of Information & Communication Technology",
      location: "AI Research Lab",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Python programming background"],
      contactEmail: "ai.workshop@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/pytorch",
      tags: ["PyTorch", "AI", "Computer Vision"],
    },
    {
      title: "Food Safety HACCP Certification Training Course",
      description: "Official training course on Hazard Analysis Critical Control Point protocols for food processing.",
      category: "Training",
      department: "Department of Biosystems Technology",
      location: "BST Seminar Hall",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["BST Undergraduates"],
      contactEmail: "haccp@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/haccp",
      tags: ["HACCP", "Food Safety", "BST"],
    },
    {
      title: "React Native Mobile App Development Workshop",
      description: "Build cross-platform iOS and Android apps using React Native and Expo framework.",
      category: "Training",
      department: "Department of Information & Communication Technology",
      location: "Computer Lab 3",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Basic JavaScript knowledge"],
      contactEmail: "mobile.dev@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/react-native",
      tags: ["React Native", "Mobile", "Expo"],
    },
    {
      title: "Industrial Automation & PLC Ladder Logic Workshop",
      description: "Program Siemens S7-1200 PLCs and SCADA human-machine interfaces.",
      category: "Training",
      department: "Department of Engineering Technology",
      location: "Mechatronics Lab",
      deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["ET 3rd year student"],
      contactEmail: "plc.workshop@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/plc",
      tags: ["PLC", "Siemens", "Automation"],
    },
    {
      title: "GIS & Remote Sensing Satellite Data Analysis",
      description: "Analyze QGIS spatial mapping and Sentinel-2 satellite imagery for land use monitoring.",
      category: "Training",
      department: "Department of Biosystems Technology",
      location: "GIS Computer Suite",
      deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Laptop with QGIS installed"],
      contactEmail: "gis.training@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/gis",
      tags: ["GIS", "QGIS", "Satellite"],
    },
    {
      title: "Technical Writing & IEEE Research Paper Preparation",
      description: "Learn LaTeX formatting, citation managers, and structured writing for IEEE journal submissions.",
      category: "Training",
      department: "General",
      location: "FoT Auditorium",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Final year students writing research thesis"],
      contactEmail: "research.writing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/ieee",
      tags: ["LaTeX", "IEEE", "Research Paper"],
    },
    {
      title: "Agile Scrum Master & Jira Certification Training",
      description: "2-day workshop on sprint planning, user stories, and Jira board management for software projects.",
      category: "Training",
      department: "Department of Information & Communication Technology",
      location: "Virtual",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Undergrad"],
      contactEmail: "agile.training@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/training/agile",
      tags: ["Agile", "Scrum", "Jira"],
    },
  ];
  training.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 5. FINANCIAL SUPPORT (10 Items)
  const financialSupport = [
    {
      title: "Student Laptop Purchasing Loan Interest Subsidy",
      description: "Zero-interest micro-loan scheme up to LKR 120,000 for purchasing personal laptops needed for online coursework.",
      category: "Financial Support",
      department: "General",
      location: "Student Affairs Branch",
      deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Undergraduate ID", "No active default loan"],
      contactEmail: "studentloans@ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/laptop-loan",
      tags: ["Laptop", "Loan", "Financial Aid"],
    },
    {
      title: "Emergency Medical & Surgical Assistance Fund",
      description: "Financial grant up to LKR 75,000 to cover emergency hospital bills or prescription costs for undergraduates.",
      category: "Financial Support",
      department: "General",
      location: "Campus Health Center",
      deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Medical report from government hospital"],
      contactEmail: "health.support@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/medical-fund",
      tags: ["Medical", "Emergency", "Health"],
    },
    {
      title: "Final Year Prototype Fabrication Component Grant",
      description: "Reimbursement up to LKR 40,000 for electronic sensors, motor drivers, or raw materials purchased for final year research projects.",
      category: "Financial Support",
      department: "Department of Engineering Technology",
      location: "Dean's Office",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Approved final year project proposal", "Original bills"],
      contactEmail: "et.grants@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/project-grant",
      tags: ["Reimbursement", "Prototype", "ET"],
    },
    {
      title: "Semester Examination Fee Exemption Waiver",
      description: "Full waiver of repeat or late exam registration fees for students from documented low-income households.",
      category: "Financial Support",
      department: "General",
      location: "Examination Branch",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Grama Niladhari income certificate"],
      contactEmail: "exams@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/exam-waiver",
      tags: ["Exam Fee", "Waiver", "Financial Need"],
    },
    {
      title: "Subsidized Campus Canteen Meal Ticket Voucher Scheme",
      description: "Monthly voucher booklet granting free daily lunch meals at the technology campus canteens.",
      category: "Financial Support",
      department: "General",
      location: "Student Welfare Committee",
      deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Student Welfare application form"],
      contactEmail: "welfare@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/canteen-voucher",
      tags: ["Food", "Canteen", "Voucher"],
    },
    {
      title: "Disability Assistive Technology Equipment Subsidy",
      description: "Direct funding for purchasing specialized accessories like braille displays, ergonomic keyboards, or hearing aid batteries.",
      category: "Financial Support",
      department: "General",
      location: "Accessibility Resource Unit",
      deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Accessibility needs registration"],
      contactEmail: "access@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/assistive-tech",
      tags: ["Accessibility", "Assistive Tech", "Disability"],
    },
    {
      title: "Research Conference Paper Registration Grant",
      description: "Funding up to LKR 30,000 covering registration fees for undergraduates presenting research papers at peer-reviewed IEEE conferences.",
      category: "Financial Support",
      department: "Department of Information & Communication Technology",
      location: "ICT Head's Office",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Accepted conference paper notification"],
      contactEmail: "ict.research@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/conference-grant",
      tags: ["IEEE", "Conference", "Research"],
    },
    {
      title: "Temporary Hostel Fee Relief Grant",
      description: "One-semester hostel fee waiver for students experiencing sudden family financial hardship.",
      category: "Financial Support",
      department: "General",
      location: "Sub-Warden Office",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Hostel resident ID", "Financial statement"],
      contactEmail: "hostel.welfare@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/hostel-relief",
      tags: ["Hostel", "Relief", "Waiver"],
    },
    {
      title: "Software Tool & Cloud Credits Voucher (AWS/JetBrains)",
      description: "Free LKR 50,000 equivalent vouchers for AWS cloud hosting and JetBrains IDE licenses for student developers.",
      category: "Financial Support",
      department: "Department of Information & Communication Technology",
      location: "Virtual",
      deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["University email address"],
      contactEmail: "cloud.credits@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/cloud-credits",
      tags: ["AWS", "JetBrains", "Cloud Credits"],
    },
    {
      title: "Student Startup Seed Capital Micro-Grant",
      description: "Seed funding of LKR 100,000 to launch campus-born tech initiatives and prototype products.",
      category: "Financial Support",
      department: "General",
      location: "FoT Incubator Cell",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Team of 2+ FoT students", "Pitch deck"],
      contactEmail: "incubator@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/support/seed-capital",
      tags: ["Startup", "Incubator", "Seed Capital"],
    },
  ];
  financialSupport.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 6. MENTAL HEALTH (10 Items)
  const mentalHealth = [
    {
      title: "Campus Confidential Counseling & Wellness Sessions",
      description: "Free 1-on-1 confidential counseling with qualified university psychologists to discuss exam stress, anxiety, or personal difficulties.",
      category: "Mental Health",
      department: "General",
      location: "Student Wellness Center, Building C",
      deadline: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Undergraduate ID"],
      contactEmail: "counselor@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/counseling",
      tags: ["Counseling", "Wellness", "Confidential"],
    },
    {
      title: "Mindfulness & Exam Stress Relief Workshop Series",
      description: "Weekly guided meditation, breathing techniques, and time-management strategies for end-of-semester exam preparation.",
      category: "Mental Health",
      department: "General",
      location: "FoT Auditorium / Virtual",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Open to all students"],
      contactEmail: "mindfulness@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/mindfulness",
      tags: ["Mindfulness", "Exam Stress", "Meditation"],
    },
    {
      title: "Peer Mental Health Support Group & Buddy Network",
      description: "Student-led peer support network connecting senior undergraduates with new batch students for academic and social adaptation.",
      category: "Mental Health",
      department: "General",
      location: "Student Activity Center",
      deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Registration form"],
      contactEmail: "peer.support@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/peer-group",
      tags: ["Peer Support", "Buddy System", "Mental Health"],
    },
    {
      title: "24/7 Crisis Hotline & Remote Emotional Support",
      description: "Round-the-clock emergency telephone hotline for students experiencing severe distress or crisis.",
      category: "Mental Health",
      department: "General",
      location: "Phone / Remote",
      deadline: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Immediate hotline: 041-2292299"],
      contactEmail: "crisis@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/hotline",
      tags: ["Hotline", "Crisis", "24/7"],
    },
    {
      title: "Sleep Hygiene & Screen Fatigue Management Clinic",
      description: "Interactive session addressing late-night coding burnout, blue-light screen fatigue, and healthy sleep routines.",
      category: "Mental Health",
      department: "Department of Information & Communication Technology",
      location: "ICT Seminar Room",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["ICT / ET students"],
      contactEmail: "wellness@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/sleep-clinic",
      tags: ["Sleep", "Burnout", "Screen Fatigue"],
    },
    {
      title: "Art Therapy & Creative Expression Workshop",
      description: "Relaxing weekend art therapy sessions using painting and pottery as stress-buster outlets.",
      category: "Mental Health",
      department: "General",
      location: "Student Common Room",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["No prior art skills required"],
      contactEmail: "art.therapy@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/art-therapy",
      tags: ["Art Therapy", "Stress Relief", "Creative"],
    },
    {
      title: "Overcoming Imposter Syndrome in Tech Seminars",
      description: "Lecturer and alumni panel discussion sharing personal experiences with self-doubt during engineering studies.",
      category: "Mental Health",
      department: "Department of Engineering Technology",
      location: "ET Main Hall",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["All FoT Undergrads"],
      contactEmail: "seminars@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/imposter-syndrome",
      tags: ["Imposter Syndrome", "Confidence", "Tech Panel"],
    },
    {
      title: "Yoga & Physical Movement for Posture Relief",
      description: "Morning yoga classes focusing on neck and back pain relief for students sitting long hours at computer workstations.",
      category: "Mental Health",
      department: "General",
      location: "Technology Campus Gymnasium",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Comfortable exercise clothes"],
      contactEmail: "yoga@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/yoga",
      tags: ["Yoga", "Posture", "Physical Health"],
    },
    {
      title: "Work-Life Balance & Time Management Masterclass",
      description: "Practical strategies for balancing coursework, part-time jobs, and personal relaxation.",
      category: "Mental Health",
      department: "General",
      location: "Auditorium",
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Registration required"],
      contactEmail: "timemanagement@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/time-management",
      tags: ["Time Management", "Work-Life Balance", "Productivity"],
    },
    {
      title: "Inclusive Group Support for Differently Abled Undergraduates",
      description: "Safe sharing circle and barrier advocacy group specifically for students with physical or sensory disabilities.",
      category: "Mental Health",
      department: "General",
      location: "Accessible Resource Room",
      deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Registered disabled students"],
      contactEmail: "disability.support@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/mental-health/disability-support",
      tags: ["Disability", "Inclusion", "Support Group"],
    },
  ];
  mentalHealth.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 7. ACCOMMODATION (10 Items)
  const accommodation = [
    {
      title: "Subsidized On-Campus University Hostel Allocation 2026",
      description: "Official university hostel rooms for 1st & 4th year undergraduates within 200m walking distance to FoT lecture halls.",
      category: "Accommodation",
      department: "General",
      location: "Kamburupitiya Tech Campus Hostel",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Full-time FoT undergraduate", "Distance > 50km"],
      contactEmail: "hosteloffice@ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/hostel-apply",
      tags: ["Hostel", "On-Campus", "Subsidized"],
    },
    {
      title: "Wheelchair Accessible Ground Floor Boarding House",
      description: "Specially adapted private boarding house with wide doorways, ramp access, and roll-in shower, located 500m from campus.",
      category: "Accommodation",
      department: "General",
      location: "Kamburupitiya Town (500m to FoT)",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Undergraduates with mobility impairments"],
      contactEmail: "access.housing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/accessible-house",
      tags: ["Wheelchair", "Accessible", "Ground Floor"],
    },
    {
      title: "Shared Female Tech Student House near Campus",
      description: "Furnished 4-bedroom house with study desks, high-speed Wi-Fi, and 24/7 security gate. LKR 6,500/month per student.",
      category: "Accommodation",
      department: "Department of Information & Communication Technology",
      location: "Kamburupitiya Junction",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Female FoT students"],
      contactEmail: "femalehousing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/female-boarding",
      tags: ["Female Hostel", "Wi-Fi", "Boarding"],
    },
    {
      title: "Quiet Study Boarding House for Final Year Project Students",
      description: "Dedicated quiet environment for students writing research theses with air-conditioned study hall and generator backup.",
      category: "Accommodation",
      department: "General",
      location: "Kamburupitiya North",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Final year undergraduate"],
      contactEmail: "quiet.housing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/quiet-boarding",
      tags: ["Quiet Study", "Generator", "Thesis"],
    },
    {
      title: "Matara City Shared Apartment (Near Railway Station)",
      description: "Ideal for students commuting between Matara city center and technology campus via campus shuttle bus.",
      category: "Accommodation",
      department: "General",
      location: "Matara Town (Near Station)",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Student ID"],
      contactEmail: "matarahousing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/matara-flat",
      tags: ["Matara", "Station", "Apartment"],
    },
    {
      title: "Low-Cost Subsidized Boarding Rooms for Mahapola Recipients",
      description: "Boarding rooms at discounted rate of LKR 4,000/month verified by university welfare committee.",
      category: "Accommodation",
      department: "General",
      location: "Kamburupitiya Area",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Mahapola Bursary Card"],
      contactEmail: "welfare.housing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/low-cost",
      tags: ["Mahapola", "Low Cost", "Subsidized"],
    },
    {
      title: "Male Engineering Tech Student Boarding Annex",
      description: "Spacious annex for 3 male ET students with workshop storage space for final year hardware models.",
      category: "Accommodation",
      department: "Department of Engineering Technology",
      location: "Near FoT Gate 2",
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Male ET Undergraduates"],
      contactEmail: "et.housing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/male-annex",
      tags: ["Annex", "ET", "Male Boarding"],
    },
    {
      title: "Short-Term Exam Season Guest Accommodation",
      description: "Weekly room rentals for distance commuting students during 2-week semester examination period.",
      category: "Accommodation",
      department: "General",
      location: "Kamburupitiya Campus Lodge",
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Exam hall index number"],
      contactEmail: "shortterm@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/exam-stay",
      tags: ["Short-Term", "Exam Season", "Lodge"],
    },
    {
      title: "Eco-Friendly Boarding with Solar Power & Solar Hot Water",
      description: "Modern green boarding house powered 100% by solar PV panels with solar hot water showers.",
      category: "Accommodation",
      department: "Department of Biosystems Technology",
      location: "Kamburupitiya East",
      deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Undergrad"],
      contactEmail: "greenhousing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/green-boarding",
      tags: ["Solar", "Eco-Friendly", "Green"],
    },
    {
      title: "Emergency Temporary Shelter Assistance for Homeless/Stranded Students",
      description: "Immediate 3-day emergency stay voucher for students facing sudden eviction or domestic emergency.",
      category: "Accommodation",
      department: "General",
      location: "Campus Welfare Office",
      deadline: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Immediate referral by Warden"],
      contactEmail: "emergency.housing@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/accommodation/emergency-stay",
      tags: ["Emergency", "Shelter", "Welfare"],
    },
  ];
  accommodation.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 8. TRANSPORT (10 Items)
  const transport = [
    {
      title: "Campus Shuttle Bus Service (Matara Station <-> FoT Campus)",
      description: "Scheduled daily shuttle bus running 6 times a day connecting Matara Railway Station directly to Kamburupitiya FoT Campus.",
      category: "Transport",
      department: "General",
      location: "Matara Station / FoT Campus",
      deadline: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Student Travel Pass (LKR 50 per trip)"],
      contactEmail: "transport@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/shuttle-bus",
      tags: ["Shuttle Bus", "Matara", "Campus Transport"],
    },
    {
      title: "Wheelchair Accessible Van Transport Scheme",
      description: "Dedicated hydraulic lift van service for mobility impaired undergraduates commuting between hostels and lecture halls.",
      category: "Transport",
      department: "General",
      location: "FoT Campus & Hostels",
      deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Registered mobility impaired student"],
      contactEmail: "access.transport@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/accessible-van",
      tags: ["Wheelchair Van", "Accessible", "Hydraulic Lift"],
    },
    {
      title: "Subsidized Sri Lanka CTB Student Bus Pass Scheme",
      description: "Get 50% discount on monthly public SLTB bus fares on all routes across Southern Province.",
      category: "Transport",
      department: "General",
      location: "Matara CTB Depot",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["CTB Bus Pass Application", "Student ID"],
      contactEmail: "sltb.pass@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/ctb-pass",
      tags: ["Bus Pass", "CTB", "Discount"],
    },
    {
      title: "Campus Bicycle Sharing & Rental Scheme",
      description: "Rent smart bicycles for LKR 20/hour to commute between Building A, B, and the agricultural test fields.",
      category: "Transport",
      department: "General",
      location: "FoT Main Gate Cycle Stand",
      deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT Student ID barcode"],
      contactEmail: "cycles@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/bicycles",
      tags: ["Bicycle", "Green Commute", "Campus"],
    },
    {
      title: "Late Night Exam Carpool & Security Escort",
      description: "Organized group carpool and security escort service for students studying late at ICT labs until midnight.",
      category: "Transport",
      department: "Department of Information & Communication Technology",
      location: "ICT Lab Complex",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Late night lab permit"],
      contactEmail: "security@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/carpool",
      tags: ["Carpool", "Late Night", "Security"],
    },
    {
      title: "Inter-Campus Express Bus (Wellamadama <-> Technology Campus)",
      description: "Direct morning and evening express bus connecting Main University Campus (Wellamadama) with Technology Campus.",
      category: "Transport",
      department: "General",
      location: "Wellamadama / Kamburupitiya",
      deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["University ID"],
      contactEmail: "intercampus@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/express-bus",
      tags: ["Express Bus", "Wellamadama", "Inter-Campus"],
    },
    {
      title: "Student Railway Commuter Discount Concession Card",
      description: "Annual Sri Lanka Railways concession pass granting 60% discount on 2nd and 3rd class train tickets.",
      category: "Transport",
      department: "General",
      location: "Matara Railway Station",
      deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Railway Concession Form from Dean"],
      contactEmail: "railways@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/railway-pass",
      tags: ["Train", "Railway", "Concession"],
    },
    {
      title: "Electric Scooter Charging Stations & Parking Permits",
      description: "Free EV charging stations and dedicated shaded parking slots for student electric scooters.",
      category: "Transport",
      department: "Department of Engineering Technology",
      location: "Building B Parking",
      deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["EV Scooter registration"],
      contactEmail: "ev.parking@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/ev-charging",
      tags: ["Electric Scooter", "EV", "Charging"],
    },
    {
      title: "Rainy Season Emergency Umbrella & Shuttle Service",
      description: "Golf cart shuttle service operational during heavy monsoon rains to transport students dry between lecture blocks.",
      category: "Transport",
      department: "General",
      location: "Campus Pathway Network",
      deadline: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Operates during rainy days"],
      contactEmail: "monsoon@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/monsoon-shuttle",
      tags: ["Monsoon", "Golf Cart", "Rain"],
    },
    {
      title: "Field Trip & Industrial Visit Bus Grant",
      description: "University funded buses for student batches visiting factories in Colombo, Biyagama, or Kandy.",
      category: "Transport",
      department: "General",
      location: "FoT Transport Pool",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Lecturer batch trip request"],
      contactEmail: "fieldtrips@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/transport/field-trips",
      tags: ["Field Trip", "Industrial Visit", "Bus"],
    },
  ];
  transport.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 9. EVENTS (10 Items)
  const events = [
    {
      title: "Technovate 2026 - Annual Technology Innovation Hackathon",
      description: "24-hour hackathon bringing together ICT, ET, and BST students to prototype solutions for real-world Sri Lankan problems.",
      category: "Events",
      department: "General",
      location: "FoT Main Auditorium",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Teams of 3-5 FoT students", "Bring laptop"],
      contactEmail: "technovate@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/technovate2026",
      tags: ["Hackathon", "Technovate", "Coding", "Prize"],
    },
    {
      title: "Robofest Ruhuna 2026 Robotics Championship",
      description: "National robotics contest featuring Line Follower, Autonomous Maze Solver, and Mobile Robot competitions.",
      category: "Events",
      department: "Department of Engineering Technology",
      location: "ET Gymnasium Arena",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Open to school & university teams"],
      contactEmail: "robofest@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/robofest2026",
      tags: ["Robotics", "Robofest", "ET", "Robots"],
    },
    {
      title: "FoT Annual Industrial Career Fair 2026",
      description: "Meet top tech employers including Virtusa, WSO2, Dialog, Sysco LABS, and 40+ Sri Lankan IT and engineering firms.",
      category: "Events",
      department: "General",
      location: "FoT Grounds & Exhibition Center",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Printed copies of CV"],
      contactEmail: "careerfair@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/careerfair2026",
      tags: ["Career Fair", "Jobs", "CV", "Networking"],
    },
    {
      title: "International Research Symposium on Technology (IRST 2026)",
      description: "Academic conference showcasing research papers in ICT, Mechatronics, Bio-processing, and Green Tech.",
      category: "Events",
      department: "General",
      location: "FoT Conference Center",
      deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Registration required"],
      contactEmail: "irst2026@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/irst2026",
      tags: ["Symposium", "Research", "IRST", "Conference"],
    },
    {
      title: "Smart Agriculture & Agri-Tech Exhibition 2026",
      description: "Exhibition showcasing hydroponics systems, drone spraying, and post-harvest machinery developed by BST students.",
      category: "Events",
      department: "Department of Biosystems Technology",
      location: "FoT Agri Demonstration Park",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Free entry for students and public"],
      contactEmail: "agritech@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/agritech2026",
      tags: ["Agri-Tech", "Drones", "BST", "Exhibition"],
    },
    {
      title: "Cyber Security CTF (Capture The Flag) Competition",
      description: "Jeopardy-style CTF challenge testing web security, cryptography, reverse engineering, and forensic analysis.",
      category: "Events",
      department: "Department of Information & Communication Technology",
      location: "Virtual & ICT Lab 2",
      deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Individual or teams of 2"],
      contactEmail: "ctf@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/ctf2026",
      tags: ["CTF", "Cyber Security", "Hacking"],
    },
    {
      title: "Faculty Cultural Night & Musical Extravaganza",
      description: "Annual cultural show celebrating music, drama, and traditional dance performances by technology undergraduates.",
      category: "Events",
      department: "General",
      location: "Campus Amphitheater",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Free student ticket"],
      contactEmail: "cultural@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/cultural-night",
      tags: ["Cultural", "Music", "Drama", "Arts"],
    },
    {
      title: "FoT Inter-Departmental Sports & e-Sports League",
      description: "Cricket, Futsal, Badminton, and Valorant/PUBG Mobile esports tournament between ICT, ET, and BST.",
      category: "Events",
      department: "General",
      location: "Campus Grounds & Sports Center",
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Department team registration"],
      contactEmail: "sports@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/sports-league",
      tags: ["Sports", "Esports", "Tournament"],
    },
    {
      title: "Open Source Software Day & Linux Install-Fest",
      description: "Get hands-on help installing Ubuntu/Fedora Linux, configuring Git, and making your first GitHub open-source PR.",
      category: "Events",
      department: "Department of Information & Communication Technology",
      location: "ICT Lab 1",
      deadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Bring laptop and USB drive"],
      contactEmail: "oss@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/linux-day",
      tags: ["Linux", "Open Source", "GitHub"],
    },
    {
      title: "Faculty Alumni Tech Talk & Panel Discussion",
      description: "Senior FoT graduates working at Google, WSO2, and Dialog share career advice and interview strategies.",
      category: "Events",
      department: "General",
      location: "Auditorium & Live Stream",
      deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Open Q&A for all batches"],
      contactEmail: "techtalk@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/events/techtalk",
      tags: ["Alumni", "Tech Talk", "Career Advice"],
    },
  ];
  events.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  // 10. VOLUNTEERING (10 Items)
  const volunteering = [
    {
      title: "Rural School Computer Literacy Volunteer Mentor",
      description: "Teach basic IT skills, Scratch coding, and internet safety to middle school students in rural Matara schools.",
      category: "Volunteering",
      department: "Department of Information & Communication Technology",
      location: "Kamburupitiya Rural Schools",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["FoT ICT/ET Student", "Enthusiasm for teaching"],
      contactEmail: "community.it@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/school-it",
      tags: ["Volunteering", "Teaching", "Community"],
    },
    {
      title: "Visually Impaired Audio Book Reader & Converter",
      description: "Volunteer to record audio chapter readings of university textbooks for visually impaired undergraduates.",
      category: "Volunteering",
      department: "General",
      location: "Audio Recording Studio, FoT Library",
      deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Clear Sinhala / English voice recording"],
      contactEmail: "audiobooks@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/audio-books",
      tags: ["Accessibility", "Audio Books", "Blind Support"],
    },
    {
      title: "Matara Coastal & Beach Plastic Clean-Up Drive",
      description: "Join weekend environmental volunteer drive collecting micro-plastics and logging waste data along Matara coast.",
      category: "Volunteering",
      department: "General",
      location: "Matara Beach Park",
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Gloves & bags provided"],
      contactEmail: "green.team@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/beach-cleanup",
      tags: ["Clean-Up", "Eco", "Environment"],
    },
    {
      title: "Campus Green Eco-Tech Tree Planting Volunteer",
      description: "Help plant 500 indigenous shade trees across the technology campus grounds.",
      category: "Volunteering",
      department: "Department of Biosystems Technology",
      location: "FoT Campus Grounds",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Open to all students"],
      contactEmail: "ecotech@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/tree-planting",
      tags: ["Tree Planting", "Green", "BST"],
    },
    {
      title: "Blood Donation Camp Volunteer Organizer",
      description: "Assist with donor registration, refreshment distribution, and crowd control for annual campus blood drive.",
      category: "Volunteering",
      department: "General",
      location: "Student Activity Center",
      deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Reliable event organizer"],
      contactEmail: "blooddrive@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/blood-drive",
      tags: ["Blood Donation", "Red Cross", "Health"],
    },
    {
      title: "Disaster Emergency Relief Coordinator",
      description: "Volunteer to sort and package flood relief supplies for local communities affected by heavy monsoons.",
      category: "Volunteering",
      department: "General",
      location: "FoT Gymnasium",
      deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["On-call availability during rain alerts"],
      contactEmail: "disaster.relief@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/flood-relief",
      tags: ["Flood Relief", "Disaster", "Community"],
    },
    {
      title: "Elderly Home Technology Helper & Smartphone Coach",
      description: "Visit local Matara senior citizen home to help elderly residents connect with family via WhatsApp and Zoom.",
      category: "Volunteering",
      department: "Department of Information & Communication Technology",
      location: "Matara Senior Home",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Patience and friendly attitude"],
      contactEmail: "senior.it@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/senior-it",
      tags: ["Elderly Care", "WhatsApp", "Social"],
    },
    {
      title: "Animal Welfare & Stray Dog Vaccination Drive",
      description: "Assist veterinary team with anti-rabies vaccination and feeding drive for campus stray dogs.",
      category: "Volunteering",
      department: "General",
      location: "Campus Grounds",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Animal lovers"],
      contactEmail: "paws@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/animal-welfare",
      tags: ["Animal Welfare", "Rabies", "Paws"],
    },
    {
      title: "Youth STEM Workshop Facilitator for School Students",
      description: "Demonstrate simple electronics, water filtration, and solar toys to visiting high school science students.",
      category: "Volunteering",
      department: "Department of Engineering Technology",
      location: "FoT Innovation Cell",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["ET / BST Undergrad"],
      contactEmail: "stem.youth@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/stem-youth",
      tags: ["STEM", "High School", "Demonstrator"],
    },
    {
      title: "Campus Access Barrier Survey & ARIA Auditor Volunteer",
      description: "Walk around campus to audit physical ramp slopes and test screen reader compatibility on university portals.",
      category: "Volunteering",
      department: "General",
      location: "FoT Campus",
      deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
      requirements: ["Interest in accessibility"],
      contactEmail: "barrier.audit@fot.ruh.ac.lk",
      applicationUrl: "https://fot.ruh.ac.lk/volunteering/barrier-audit",
      tags: ["Accessibility", "Audit", "Inclusion"],
    },
  ];
  volunteering.forEach((item) => dataset.push({ ...item, _id: `opp_seed_${idCounter++}` }));

  return dataset;
};

module.exports = generateCategoryData;
